### ISSUE TITLE
Define learning objectives and key concepts

### ISSUE THREAD

**Issue by shelbyahrendt** [espin-2020/fluvial#14]
It might be nice to structure our Jupyter notebook around the learning objectives and key concepts (similar to this format: https://csdms.colorado.edu/wiki/Lab-0012). Can we brainstorm/list our objectives & concepts below?

**Comment by shelbyahrendt** [comment]
some ideas here: 
https://docs.google.com/document/d/1ZBxy-HDRFBK47puen_pfs5bNqNG0J2pF7H3Xe6jjEUY/edit

**Comment by shelbyahrendt** [comment]
Possible Objectives:
- exploring parameters that influence flooding including: rainfall intensity, rainfall distribution, sediment supply, and infiltration properties on overbank flow on a floodplain
- coupling models
- coupling grids of different resolution

**Comment by shelbyahrendt** [comment]
should we note that our model hasn’t been tested for physical correctness and/or stability?

**Comment by ericbarefoot** [comment]
I like the idea of just focusing the notebook on model coupling. Maybe an outline could be:
1. Introduce two model grid types (network and rectilinear)
2. Connecting these two grids by layering them on top of each other. 
3. Connecting two rectilinear grids by having output of one feed into the input for another.

**Comment by KarstModel** [comment]
Starting point for a structure for objectives to include in README:

A. Software engineering objectives

Through implementing this coupled notebook, students will be able to design a jupyter notebook to:

- couple components within the Landlab framework.
- couple grids of different resolutions and different grid types using a line-framework (see image below). 


```
1. Introduce two model grid types (network and rectilinear)
2. Connecting these two grids by layering them on top of each other.
3. Connecting two rectilinear grids by having output of one feed into the input for another.
```

B. Fluvial geomorphology objectives

Given a structured Jupyter notebook with parameters that can vary, students will have the opportunity to explore the synergistic effects of:

```
- rainfall intensity
- rainfall distribution
- sediment supply
- infiltration properties on overbank flow in a floodplain
```
