### ISSUE TITLE
Separate some tasks into functions for import

### ISSUE THREAD

**Issue by ericbarefoot** [espin-2020/fluvial#16]
For readability, it would be helpful for several functions to be `import`ed at the top of our tutorial. 

We can (and should) explain how these functions work and what they do in the notebook so that users aren't confused. 

As an example, we might take out the code that finds and latches the network grid to the rectilinear grid, and make that a function that can get called.

**Comment by josiearcuri** [comment]
I will come to our next meeting with some new functions, but will leave the grid node setting part to @shelbyahrendt

**Comment by shelbyahrendt** [comment]
sounds good @josiearcuri! I've been playing with creating our network in landlab using the ChannelProfiler (vs. importing the shapefile network) here: https://github.com/shelbyahrendt/landlab/blob/shelby_dev/notebooks/tutorials/network_sediment_transporter/create_network_from_raster.ipynb (although it needs some work to get "up-to-snuff" and functionalized) @hgudipati  and I are planning to team-tackle this!

**Comment by josiearcuri** [comment]
I'm working on functions for visualization - hopefully I can get a pull request up on Friday 10/16! If there are any suggestions for what we want to visualize differently I am very open to them
