### ISSUE TITLE
Too many shapefiles!

### ISSUE THREAD

**Issue by KarstModel** [espin-2020/fluvial#7]
There are too many shapefiles in the master branch and the data folder. I would like to delete the ones we are not using. It looks like hugo_links.shp is the only shapefile being used by our code. Can someone please confirm this before I start deleting files to clean up our repo?

**Comment by hgudipati** [comment]
Thank you for opening this issue. I agree that hugo_links.shp is the only shapefile that is being used in the code right now.

**Comment by KarstModel** [comment]
Thank you for double checking that. Deleting extraneous files and closing issue.
